### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by ccamara** [mapcolabora/osm_imports_preparations#3]
- [x] Configure sphinx or https://www.mkdocs.org/ to generate documentation
- [x] Generate documentation from functions 
- [x] Document the import process for trees (use [this example](https://wiki.openstreetmap.org/wiki/Import_information_and_care_points_for_women_and_LGTBI_collectives_in_Catalunya#Data_Preparation) as reference, attaching city council's authorisation)

References:

* https://realpython.com/documenting-python-code/

**Comment by ccamara** [comment]
as per @gabrieldemarmiesse guidance in https://github.com/keras-team/keras-autodoc/issues/68#issuecomment-568305242 this has been solved in commit a3e5af445afd063f6837e8a424337374077272db

**Comment by ccamara** [comment]
@all-contributors please add gabrieldemarmiesse for Answering Questions

**Comment by gabrieldemarmiesse** [comment]
Happy to help :)
